// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package gpusher_srv_message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SaveGatewayUUIDRequest struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	GatewayAddr          string   `protobuf:"bytes,2,opt,name=GatewayAddr,proto3" json:"GatewayAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveGatewayUUIDRequest) Reset()         { *m = SaveGatewayUUIDRequest{} }
func (m *SaveGatewayUUIDRequest) String() string { return proto.CompactTextString(m) }
func (*SaveGatewayUUIDRequest) ProtoMessage()    {}
func (*SaveGatewayUUIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *SaveGatewayUUIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveGatewayUUIDRequest.Unmarshal(m, b)
}
func (m *SaveGatewayUUIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveGatewayUUIDRequest.Marshal(b, m, deterministic)
}
func (m *SaveGatewayUUIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveGatewayUUIDRequest.Merge(m, src)
}
func (m *SaveGatewayUUIDRequest) XXX_Size() int {
	return xxx_messageInfo_SaveGatewayUUIDRequest.Size(m)
}
func (m *SaveGatewayUUIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveGatewayUUIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveGatewayUUIDRequest proto.InternalMessageInfo

func (m *SaveGatewayUUIDRequest) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *SaveGatewayUUIDRequest) GetGatewayAddr() string {
	if m != nil {
		return m.GatewayAddr
	}
	return ""
}

type SaveAppUUIDRequest struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	AppTag               string   `protobuf:"bytes,2,opt,name=AppTag,proto3" json:"AppTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveAppUUIDRequest) Reset()         { *m = SaveAppUUIDRequest{} }
func (m *SaveAppUUIDRequest) String() string { return proto.CompactTextString(m) }
func (*SaveAppUUIDRequest) ProtoMessage()    {}
func (*SaveAppUUIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *SaveAppUUIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveAppUUIDRequest.Unmarshal(m, b)
}
func (m *SaveAppUUIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveAppUUIDRequest.Marshal(b, m, deterministic)
}
func (m *SaveAppUUIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveAppUUIDRequest.Merge(m, src)
}
func (m *SaveAppUUIDRequest) XXX_Size() int {
	return xxx_messageInfo_SaveAppUUIDRequest.Size(m)
}
func (m *SaveAppUUIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveAppUUIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveAppUUIDRequest proto.InternalMessageInfo

func (m *SaveAppUUIDRequest) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *SaveAppUUIDRequest) GetAppTag() string {
	if m != nil {
		return m.AppTag
	}
	return ""
}

type SaveExpireMsgRequest struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	MsgId                string   `protobuf:"bytes,2,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
	ExpireTime           int32    `protobuf:"varint,4,opt,name=ExpireTime,proto3" json:"ExpireTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveExpireMsgRequest) Reset()         { *m = SaveExpireMsgRequest{} }
func (m *SaveExpireMsgRequest) String() string { return proto.CompactTextString(m) }
func (*SaveExpireMsgRequest) ProtoMessage()    {}
func (*SaveExpireMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *SaveExpireMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveExpireMsgRequest.Unmarshal(m, b)
}
func (m *SaveExpireMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveExpireMsgRequest.Marshal(b, m, deterministic)
}
func (m *SaveExpireMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveExpireMsgRequest.Merge(m, src)
}
func (m *SaveExpireMsgRequest) XXX_Size() int {
	return xxx_messageInfo_SaveExpireMsgRequest.Size(m)
}
func (m *SaveExpireMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveExpireMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveExpireMsgRequest proto.InternalMessageInfo

func (m *SaveExpireMsgRequest) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *SaveExpireMsgRequest) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *SaveExpireMsgRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SaveExpireMsgRequest) GetExpireTime() int32 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

type DeleteGatewayUUIDRequest struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGatewayUUIDRequest) Reset()         { *m = DeleteGatewayUUIDRequest{} }
func (m *DeleteGatewayUUIDRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGatewayUUIDRequest) ProtoMessage()    {}
func (*DeleteGatewayUUIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *DeleteGatewayUUIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGatewayUUIDRequest.Unmarshal(m, b)
}
func (m *DeleteGatewayUUIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGatewayUUIDRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGatewayUUIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGatewayUUIDRequest.Merge(m, src)
}
func (m *DeleteGatewayUUIDRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGatewayUUIDRequest.Size(m)
}
func (m *DeleteGatewayUUIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGatewayUUIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGatewayUUIDRequest proto.InternalMessageInfo

func (m *DeleteGatewayUUIDRequest) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

type DeleteAppUUIDRequest struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	AppTag               string   `protobuf:"bytes,2,opt,name=AppTag,proto3" json:"AppTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAppUUIDRequest) Reset()         { *m = DeleteAppUUIDRequest{} }
func (m *DeleteAppUUIDRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAppUUIDRequest) ProtoMessage()    {}
func (*DeleteAppUUIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *DeleteAppUUIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAppUUIDRequest.Unmarshal(m, b)
}
func (m *DeleteAppUUIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAppUUIDRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAppUUIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAppUUIDRequest.Merge(m, src)
}
func (m *DeleteAppUUIDRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAppUUIDRequest.Size(m)
}
func (m *DeleteAppUUIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAppUUIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAppUUIDRequest proto.InternalMessageInfo

func (m *DeleteAppUUIDRequest) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *DeleteAppUUIDRequest) GetAppTag() string {
	if m != nil {
		return m.AppTag
	}
	return ""
}

type DeleteExpireMsgRequest struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	MsgId                string   `protobuf:"bytes,2,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteExpireMsgRequest) Reset()         { *m = DeleteExpireMsgRequest{} }
func (m *DeleteExpireMsgRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteExpireMsgRequest) ProtoMessage()    {}
func (*DeleteExpireMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *DeleteExpireMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteExpireMsgRequest.Unmarshal(m, b)
}
func (m *DeleteExpireMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteExpireMsgRequest.Marshal(b, m, deterministic)
}
func (m *DeleteExpireMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteExpireMsgRequest.Merge(m, src)
}
func (m *DeleteExpireMsgRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteExpireMsgRequest.Size(m)
}
func (m *DeleteExpireMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteExpireMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteExpireMsgRequest proto.InternalMessageInfo

func (m *DeleteExpireMsgRequest) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *DeleteExpireMsgRequest) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

type Respond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Respond) Reset()         { *m = Respond{} }
func (m *Respond) String() string { return proto.CompactTextString(m) }
func (*Respond) ProtoMessage()    {}
func (*Respond) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *Respond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Respond.Unmarshal(m, b)
}
func (m *Respond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Respond.Marshal(b, m, deterministic)
}
func (m *Respond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Respond.Merge(m, src)
}
func (m *Respond) XXX_Size() int {
	return xxx_messageInfo_Respond.Size(m)
}
func (m *Respond) XXX_DiscardUnknown() {
	xxx_messageInfo_Respond.DiscardUnknown(m)
}

var xxx_messageInfo_Respond proto.InternalMessageInfo

func (m *Respond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Respond) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetGatewayUUIDRequest struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGatewayUUIDRequest) Reset()         { *m = GetGatewayUUIDRequest{} }
func (m *GetGatewayUUIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetGatewayUUIDRequest) ProtoMessage()    {}
func (*GetGatewayUUIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *GetGatewayUUIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayUUIDRequest.Unmarshal(m, b)
}
func (m *GetGatewayUUIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayUUIDRequest.Marshal(b, m, deterministic)
}
func (m *GetGatewayUUIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayUUIDRequest.Merge(m, src)
}
func (m *GetGatewayUUIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetGatewayUUIDRequest.Size(m)
}
func (m *GetGatewayUUIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayUUIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayUUIDRequest proto.InternalMessageInfo

func (m *GetGatewayUUIDRequest) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

type GetAppUUIDRequest struct {
	AppTag               string   `protobuf:"bytes,1,opt,name=AppTag,proto3" json:"AppTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppUUIDRequest) Reset()         { *m = GetAppUUIDRequest{} }
func (m *GetAppUUIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppUUIDRequest) ProtoMessage()    {}
func (*GetAppUUIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *GetAppUUIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppUUIDRequest.Unmarshal(m, b)
}
func (m *GetAppUUIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppUUIDRequest.Marshal(b, m, deterministic)
}
func (m *GetAppUUIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppUUIDRequest.Merge(m, src)
}
func (m *GetAppUUIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppUUIDRequest.Size(m)
}
func (m *GetAppUUIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppUUIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppUUIDRequest proto.InternalMessageInfo

func (m *GetAppUUIDRequest) GetAppTag() string {
	if m != nil {
		return m.AppTag
	}
	return ""
}

type GetGatewayUUIDRespond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	GatewayAddr          string   `protobuf:"bytes,3,opt,name=GatewayAddr,proto3" json:"GatewayAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGatewayUUIDRespond) Reset()         { *m = GetGatewayUUIDRespond{} }
func (m *GetGatewayUUIDRespond) String() string { return proto.CompactTextString(m) }
func (*GetGatewayUUIDRespond) ProtoMessage()    {}
func (*GetGatewayUUIDRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *GetGatewayUUIDRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGatewayUUIDRespond.Unmarshal(m, b)
}
func (m *GetGatewayUUIDRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGatewayUUIDRespond.Marshal(b, m, deterministic)
}
func (m *GetGatewayUUIDRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGatewayUUIDRespond.Merge(m, src)
}
func (m *GetGatewayUUIDRespond) XXX_Size() int {
	return xxx_messageInfo_GetGatewayUUIDRespond.Size(m)
}
func (m *GetGatewayUUIDRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGatewayUUIDRespond.DiscardUnknown(m)
}

var xxx_messageInfo_GetGatewayUUIDRespond proto.InternalMessageInfo

func (m *GetGatewayUUIDRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetGatewayUUIDRespond) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetGatewayUUIDRespond) GetGatewayAddr() string {
	if m != nil {
		return m.GatewayAddr
	}
	return ""
}

type GetAppUUIDRespond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	UUIDs                []string `protobuf:"bytes,3,rep,name=UUIDs,proto3" json:"UUIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppUUIDRespond) Reset()         { *m = GetAppUUIDRespond{} }
func (m *GetAppUUIDRespond) String() string { return proto.CompactTextString(m) }
func (*GetAppUUIDRespond) ProtoMessage()    {}
func (*GetAppUUIDRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *GetAppUUIDRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppUUIDRespond.Unmarshal(m, b)
}
func (m *GetAppUUIDRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppUUIDRespond.Marshal(b, m, deterministic)
}
func (m *GetAppUUIDRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppUUIDRespond.Merge(m, src)
}
func (m *GetAppUUIDRespond) XXX_Size() int {
	return xxx_messageInfo_GetAppUUIDRespond.Size(m)
}
func (m *GetAppUUIDRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppUUIDRespond.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppUUIDRespond proto.InternalMessageInfo

func (m *GetAppUUIDRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAppUUIDRespond) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetAppUUIDRespond) GetUUIDs() []string {
	if m != nil {
		return m.UUIDs
	}
	return nil
}

func init() {
	proto.RegisterType((*SaveGatewayUUIDRequest)(nil), "gpusher.srv.message.SaveGatewayUUIDRequest")
	proto.RegisterType((*SaveAppUUIDRequest)(nil), "gpusher.srv.message.SaveAppUUIDRequest")
	proto.RegisterType((*SaveExpireMsgRequest)(nil), "gpusher.srv.message.SaveExpireMsgRequest")
	proto.RegisterType((*DeleteGatewayUUIDRequest)(nil), "gpusher.srv.message.DeleteGatewayUUIDRequest")
	proto.RegisterType((*DeleteAppUUIDRequest)(nil), "gpusher.srv.message.DeleteAppUUIDRequest")
	proto.RegisterType((*DeleteExpireMsgRequest)(nil), "gpusher.srv.message.DeleteExpireMsgRequest")
	proto.RegisterType((*Respond)(nil), "gpusher.srv.message.Respond")
	proto.RegisterType((*GetGatewayUUIDRequest)(nil), "gpusher.srv.message.GetGatewayUUIDRequest")
	proto.RegisterType((*GetAppUUIDRequest)(nil), "gpusher.srv.message.GetAppUUIDRequest")
	proto.RegisterType((*GetGatewayUUIDRespond)(nil), "gpusher.srv.message.GetGatewayUUIDRespond")
	proto.RegisterType((*GetAppUUIDRespond)(nil), "gpusher.srv.message.GetAppUUIDRespond")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xdf, 0x4e, 0xea, 0x40,
	0x10, 0xc6, 0x4f, 0x29, 0x85, 0x9c, 0x21, 0x1c, 0x0e, 0x6b, 0x25, 0x0d, 0x31, 0xa6, 0xd9, 0x0b,
	0x45, 0x89, 0x35, 0xd1, 0x17, 0x10, 0xc4, 0x10, 0x2e, 0xaa, 0x49, 0x05, 0x2f, 0xbc, 0xc0, 0x94,
	0x74, 0x53, 0x31, 0x62, 0xd7, 0x6e, 0x41, 0x7d, 0x04, 0xdf, 0xda, 0xf4, 0x8f, 0x42, 0xcb, 0xd6,
	0x16, 0xbd, 0xdb, 0xd9, 0x9d, 0xf9, 0x65, 0xbe, 0xe9, 0x7c, 0x29, 0x54, 0x67, 0x84, 0x31, 0xd3,
	0x26, 0x1a, 0x75, 0x1d, 0xcf, 0x41, 0x5b, 0x36, 0x9d, 0xb3, 0x7b, 0xe2, 0x6a, 0xcc, 0x5d, 0x68,
	0xd1, 0x13, 0xbe, 0x84, 0xc6, 0xb5, 0xb9, 0x20, 0x7d, 0xd3, 0x23, 0x2f, 0xe6, 0xdb, 0x68, 0x34,
	0xe8, 0x19, 0xe4, 0x79, 0x4e, 0x98, 0x87, 0x10, 0x14, 0xfd, 0x50, 0x11, 0x54, 0xa1, 0xf5, 0xd7,
	0x08, 0xce, 0x48, 0x85, 0x4a, 0x94, 0xd9, 0xb1, 0x2c, 0x57, 0x29, 0x04, 0x4f, 0xab, 0x57, 0xf8,
	0x0c, 0x90, 0xcf, 0xeb, 0x50, 0x9a, 0xc5, 0x6a, 0x40, 0xa9, 0x43, 0xe9, 0xd0, 0xb4, 0x23, 0x4c,
	0x14, 0x61, 0x17, 0x64, 0x9f, 0x70, 0xf1, 0x4a, 0xa7, 0x2e, 0xd1, 0x99, 0xfd, 0x1d, 0x43, 0x06,
	0x49, 0x67, 0xf6, 0xc0, 0x8a, 0x10, 0x61, 0x80, 0xfe, 0x83, 0xa8, 0x33, 0x5b, 0x11, 0x83, 0x3b,
	0xff, 0x88, 0x76, 0x01, 0x42, 0xde, 0x70, 0x3a, 0x23, 0x4a, 0x51, 0x15, 0x5a, 0x92, 0xb1, 0x72,
	0x83, 0x35, 0x50, 0x7a, 0xe4, 0x91, 0x78, 0x39, 0xe7, 0x80, 0xbb, 0x20, 0x87, 0xf9, 0xbf, 0xd0,
	0xd9, 0x85, 0x46, 0xc8, 0xf8, 0xb9, 0x52, 0x7c, 0x0c, 0x65, 0x83, 0x30, 0xea, 0x3c, 0x59, 0x7e,
	0xd1, 0xb9, 0x63, 0x91, 0xa0, 0x48, 0x32, 0x82, 0xf3, 0xe7, 0x20, 0x0a, 0x5f, 0x83, 0xc0, 0x6d,
	0xd8, 0xee, 0x13, 0x2f, 0xa7, 0xca, 0x36, 0xd4, 0xfb, 0xc4, 0x4b, 0x48, 0x5c, 0xca, 0x11, 0x62,
	0x72, 0xee, 0xd6, 0xc9, 0x1b, 0x34, 0x96, 0xdc, 0x2c, 0x71, 0x7d, 0xb3, 0xae, 0xe2, 0xdd, 0x6c,
	0x02, 0x97, 0x41, 0xf2, 0x8b, 0x98, 0x22, 0xaa, 0xa2, 0x3f, 0xbc, 0x20, 0x38, 0x79, 0x2f, 0x41,
	0x59, 0x0f, 0x6d, 0x80, 0xc6, 0x50, 0x4b, 0xd8, 0x00, 0xb5, 0x35, 0x8e, 0x5f, 0x34, 0xbe, 0x59,
	0x9a, 0x3b, 0xdc, 0xe4, 0xa8, 0x4b, 0xfc, 0x07, 0xdd, 0x40, 0x65, 0xc5, 0x16, 0x68, 0x3f, 0x95,
	0x1d, 0x9f, 0x76, 0x26, 0xf7, 0x16, 0xaa, 0x31, 0xb3, 0xa0, 0x83, 0x54, 0x72, 0x72, 0xcd, 0x32,
	0xd9, 0x13, 0xa8, 0xaf, 0x99, 0x02, 0x1d, 0x71, 0x8b, 0xd2, 0xcc, 0x93, 0xa7, 0xff, 0x98, 0x91,
	0x52, 0xfa, 0xe7, 0x99, 0x2d, 0x93, 0x3d, 0x86, 0x5a, 0xc2, 0x60, 0x29, 0xdf, 0x94, 0x6f, 0xc3,
	0x4c, 0xfe, 0x03, 0xfc, 0x8b, 0x6f, 0x3c, 0x3a, 0xe4, 0x56, 0x70, 0x0d, 0xd7, 0xcc, 0x97, 0xbb,
	0xd4, 0x02, 0xcb, 0xe5, 0x47, 0x7b, 0x69, 0xb5, 0x89, 0x09, 0x65, 0xe7, 0x45, 0xfc, 0x49, 0x29,
	0xf8, 0x45, 0x9c, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xce, 0xff, 0x71, 0x33, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageClient interface {
	SaveGatewayUUID(ctx context.Context, in *SaveGatewayUUIDRequest, opts ...grpc.CallOption) (*Respond, error)
	SaveAppUUID(ctx context.Context, in *SaveAppUUIDRequest, opts ...grpc.CallOption) (*Respond, error)
	SaveExpireMsg(ctx context.Context, in *SaveExpireMsgRequest, opts ...grpc.CallOption) (*Respond, error)
	DeleteGatewayUUID(ctx context.Context, in *DeleteGatewayUUIDRequest, opts ...grpc.CallOption) (*Respond, error)
	DeleteAppUUID(ctx context.Context, in *DeleteAppUUIDRequest, opts ...grpc.CallOption) (*Respond, error)
	DeleteExpireMsg(ctx context.Context, in *DeleteExpireMsgRequest, opts ...grpc.CallOption) (*Respond, error)
	GetGatewayUUID(ctx context.Context, in *GetGatewayUUIDRequest, opts ...grpc.CallOption) (*GetGatewayUUIDRespond, error)
	GetAppUUID(ctx context.Context, in *GetAppUUIDRequest, opts ...grpc.CallOption) (*GetAppUUIDRespond, error)
}

type messageClient struct {
	cc *grpc.ClientConn
}

func NewMessageClient(cc *grpc.ClientConn) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) SaveGatewayUUID(ctx context.Context, in *SaveGatewayUUIDRequest, opts ...grpc.CallOption) (*Respond, error) {
	out := new(Respond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.message.Message/SaveGatewayUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) SaveAppUUID(ctx context.Context, in *SaveAppUUIDRequest, opts ...grpc.CallOption) (*Respond, error) {
	out := new(Respond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.message.Message/SaveAppUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) SaveExpireMsg(ctx context.Context, in *SaveExpireMsgRequest, opts ...grpc.CallOption) (*Respond, error) {
	out := new(Respond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.message.Message/SaveExpireMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) DeleteGatewayUUID(ctx context.Context, in *DeleteGatewayUUIDRequest, opts ...grpc.CallOption) (*Respond, error) {
	out := new(Respond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.message.Message/DeleteGatewayUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) DeleteAppUUID(ctx context.Context, in *DeleteAppUUIDRequest, opts ...grpc.CallOption) (*Respond, error) {
	out := new(Respond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.message.Message/DeleteAppUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) DeleteExpireMsg(ctx context.Context, in *DeleteExpireMsgRequest, opts ...grpc.CallOption) (*Respond, error) {
	out := new(Respond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.message.Message/DeleteExpireMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetGatewayUUID(ctx context.Context, in *GetGatewayUUIDRequest, opts ...grpc.CallOption) (*GetGatewayUUIDRespond, error) {
	out := new(GetGatewayUUIDRespond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.message.Message/GetGatewayUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetAppUUID(ctx context.Context, in *GetAppUUIDRequest, opts ...grpc.CallOption) (*GetAppUUIDRespond, error) {
	out := new(GetAppUUIDRespond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.message.Message/GetAppUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServer is the server API for Message service.
type MessageServer interface {
	SaveGatewayUUID(context.Context, *SaveGatewayUUIDRequest) (*Respond, error)
	SaveAppUUID(context.Context, *SaveAppUUIDRequest) (*Respond, error)
	SaveExpireMsg(context.Context, *SaveExpireMsgRequest) (*Respond, error)
	DeleteGatewayUUID(context.Context, *DeleteGatewayUUIDRequest) (*Respond, error)
	DeleteAppUUID(context.Context, *DeleteAppUUIDRequest) (*Respond, error)
	DeleteExpireMsg(context.Context, *DeleteExpireMsgRequest) (*Respond, error)
	GetGatewayUUID(context.Context, *GetGatewayUUIDRequest) (*GetGatewayUUIDRespond, error)
	GetAppUUID(context.Context, *GetAppUUIDRequest) (*GetAppUUIDRespond, error)
}

// UnimplementedMessageServer can be embedded to have forward compatible implementations.
type UnimplementedMessageServer struct {
}

func (*UnimplementedMessageServer) SaveGatewayUUID(ctx context.Context, req *SaveGatewayUUIDRequest) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveGatewayUUID not implemented")
}
func (*UnimplementedMessageServer) SaveAppUUID(ctx context.Context, req *SaveAppUUIDRequest) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveAppUUID not implemented")
}
func (*UnimplementedMessageServer) SaveExpireMsg(ctx context.Context, req *SaveExpireMsgRequest) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveExpireMsg not implemented")
}
func (*UnimplementedMessageServer) DeleteGatewayUUID(ctx context.Context, req *DeleteGatewayUUIDRequest) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGatewayUUID not implemented")
}
func (*UnimplementedMessageServer) DeleteAppUUID(ctx context.Context, req *DeleteAppUUIDRequest) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAppUUID not implemented")
}
func (*UnimplementedMessageServer) DeleteExpireMsg(ctx context.Context, req *DeleteExpireMsgRequest) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExpireMsg not implemented")
}
func (*UnimplementedMessageServer) GetGatewayUUID(ctx context.Context, req *GetGatewayUUIDRequest) (*GetGatewayUUIDRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayUUID not implemented")
}
func (*UnimplementedMessageServer) GetAppUUID(ctx context.Context, req *GetAppUUIDRequest) (*GetAppUUIDRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppUUID not implemented")
}

func RegisterMessageServer(s *grpc.Server, srv MessageServer) {
	s.RegisterService(&_Message_serviceDesc, srv)
}

func _Message_SaveGatewayUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveGatewayUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SaveGatewayUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.message.Message/SaveGatewayUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SaveGatewayUUID(ctx, req.(*SaveGatewayUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_SaveAppUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAppUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SaveAppUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.message.Message/SaveAppUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SaveAppUUID(ctx, req.(*SaveAppUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_SaveExpireMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveExpireMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SaveExpireMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.message.Message/SaveExpireMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SaveExpireMsg(ctx, req.(*SaveExpireMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_DeleteGatewayUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGatewayUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).DeleteGatewayUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.message.Message/DeleteGatewayUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).DeleteGatewayUUID(ctx, req.(*DeleteGatewayUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_DeleteAppUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).DeleteAppUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.message.Message/DeleteAppUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).DeleteAppUUID(ctx, req.(*DeleteAppUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_DeleteExpireMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExpireMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).DeleteExpireMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.message.Message/DeleteExpireMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).DeleteExpireMsg(ctx, req.(*DeleteExpireMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetGatewayUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetGatewayUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.message.Message/GetGatewayUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetGatewayUUID(ctx, req.(*GetGatewayUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetAppUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetAppUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.message.Message/GetAppUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetAppUUID(ctx, req.(*GetAppUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Message_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gpusher.srv.message.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveGatewayUUID",
			Handler:    _Message_SaveGatewayUUID_Handler,
		},
		{
			MethodName: "SaveAppUUID",
			Handler:    _Message_SaveAppUUID_Handler,
		},
		{
			MethodName: "SaveExpireMsg",
			Handler:    _Message_SaveExpireMsg_Handler,
		},
		{
			MethodName: "DeleteGatewayUUID",
			Handler:    _Message_DeleteGatewayUUID_Handler,
		},
		{
			MethodName: "DeleteAppUUID",
			Handler:    _Message_DeleteAppUUID_Handler,
		},
		{
			MethodName: "DeleteExpireMsg",
			Handler:    _Message_DeleteExpireMsg_Handler,
		},
		{
			MethodName: "GetGatewayUUID",
			Handler:    _Message_GetGatewayUUID_Handler,
		},
		{
			MethodName: "GetAppUUID",
			Handler:    _Message_GetAppUUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
