// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package gpusher_srv_gateway

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewRequest struct {
	AppId                int32    `protobuf:"varint,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	UUid                 string   `protobuf:"bytes,2,opt,name=UUid,proto3" json:"UUid,omitempty"`
	Key                  int32    `protobuf:"varint,3,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewRequest) Reset()         { *m = NewRequest{} }
func (m *NewRequest) String() string { return proto.CompactTextString(m) }
func (*NewRequest) ProtoMessage()    {}
func (*NewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *NewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRequest.Unmarshal(m, b)
}
func (m *NewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRequest.Marshal(b, m, deterministic)
}
func (m *NewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRequest.Merge(m, src)
}
func (m *NewRequest) XXX_Size() int {
	return xxx_messageInfo_NewRequest.Size(m)
}
func (m *NewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewRequest proto.InternalMessageInfo

func (m *NewRequest) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *NewRequest) GetUUid() string {
	if m != nil {
		return m.UUid
	}
	return ""
}

func (m *NewRequest) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

type CloseRequest struct {
	AppId                int32    `protobuf:"varint,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	UUid                 string   `protobuf:"bytes,2,opt,name=UUid,proto3" json:"UUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseRequest) Reset()         { *m = CloseRequest{} }
func (m *CloseRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRequest) ProtoMessage()    {}
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CloseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRequest.Unmarshal(m, b)
}
func (m *CloseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRequest.Marshal(b, m, deterministic)
}
func (m *CloseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRequest.Merge(m, src)
}
func (m *CloseRequest) XXX_Size() int {
	return xxx_messageInfo_CloseRequest.Size(m)
}
func (m *CloseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRequest proto.InternalMessageInfo

func (m *CloseRequest) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *CloseRequest) GetUUid() string {
	if m != nil {
		return m.UUid
	}
	return ""
}

type PushOneRequest struct {
	AppId                int32    `protobuf:"varint,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	UUid                 string   `protobuf:"bytes,2,opt,name=UUid,proto3" json:"UUid,omitempty"`
	MsgId                string   `protobuf:"bytes,3,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushOneRequest) Reset()         { *m = PushOneRequest{} }
func (m *PushOneRequest) String() string { return proto.CompactTextString(m) }
func (*PushOneRequest) ProtoMessage()    {}
func (*PushOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *PushOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushOneRequest.Unmarshal(m, b)
}
func (m *PushOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushOneRequest.Marshal(b, m, deterministic)
}
func (m *PushOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushOneRequest.Merge(m, src)
}
func (m *PushOneRequest) XXX_Size() int {
	return xxx_messageInfo_PushOneRequest.Size(m)
}
func (m *PushOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushOneRequest proto.InternalMessageInfo

func (m *PushOneRequest) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *PushOneRequest) GetUUid() string {
	if m != nil {
		return m.UUid
	}
	return ""
}

func (m *PushOneRequest) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *PushOneRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *PushOneRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PushAppRequest struct {
	AppId                int32    `protobuf:"varint,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	MsgId                string   `protobuf:"bytes,2,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushAppRequest) Reset()         { *m = PushAppRequest{} }
func (m *PushAppRequest) String() string { return proto.CompactTextString(m) }
func (*PushAppRequest) ProtoMessage()    {}
func (*PushAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *PushAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushAppRequest.Unmarshal(m, b)
}
func (m *PushAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushAppRequest.Marshal(b, m, deterministic)
}
func (m *PushAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushAppRequest.Merge(m, src)
}
func (m *PushAppRequest) XXX_Size() int {
	return xxx_messageInfo_PushAppRequest.Size(m)
}
func (m *PushAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushAppRequest proto.InternalMessageInfo

func (m *PushAppRequest) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *PushAppRequest) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *PushAppRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *PushAppRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PushAllRequest struct {
	MsgId                string   `protobuf:"bytes,1,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushAllRequest) Reset()         { *m = PushAllRequest{} }
func (m *PushAllRequest) String() string { return proto.CompactTextString(m) }
func (*PushAllRequest) ProtoMessage()    {}
func (*PushAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *PushAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushAllRequest.Unmarshal(m, b)
}
func (m *PushAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushAllRequest.Marshal(b, m, deterministic)
}
func (m *PushAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushAllRequest.Merge(m, src)
}
func (m *PushAllRequest) XXX_Size() int {
	return xxx_messageInfo_PushAllRequest.Size(m)
}
func (m *PushAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushAllRequest proto.InternalMessageInfo

func (m *PushAllRequest) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *PushAllRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *PushAllRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Respond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Respond) Reset()         { *m = Respond{} }
func (m *Respond) String() string { return proto.CompactTextString(m) }
func (*Respond) ProtoMessage()    {}
func (*Respond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *Respond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Respond.Unmarshal(m, b)
}
func (m *Respond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Respond.Marshal(b, m, deterministic)
}
func (m *Respond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Respond.Merge(m, src)
}
func (m *Respond) XXX_Size() int {
	return xxx_messageInfo_Respond.Size(m)
}
func (m *Respond) XXX_DiscardUnknown() {
	xxx_messageInfo_Respond.DiscardUnknown(m)
}

var xxx_messageInfo_Respond proto.InternalMessageInfo

func (m *Respond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Respond) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*NewRequest)(nil), "gpusher.srv.gateway.NewRequest")
	proto.RegisterType((*CloseRequest)(nil), "gpusher.srv.gateway.CloseRequest")
	proto.RegisterType((*PushOneRequest)(nil), "gpusher.srv.gateway.PushOneRequest")
	proto.RegisterType((*PushAppRequest)(nil), "gpusher.srv.gateway.PushAppRequest")
	proto.RegisterType((*PushAllRequest)(nil), "gpusher.srv.gateway.PushAllRequest")
	proto.RegisterType((*Respond)(nil), "gpusher.srv.gateway.Respond")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xff, 0xe9, 0x36, 0xff, 0x90, 0x41, 0x44, 0x46, 0x0f, 0x8b, 0x14, 0xac, 0xf1, 0xd2,
	0x53, 0x04, 0xbd, 0x78, 0x2d, 0x05, 0xb5, 0x4a, 0xab, 0x04, 0x7b, 0x15, 0x22, 0x19, 0xd2, 0x42,
	0x9a, 0x5d, 0xbb, 0x5b, 0x4b, 0xbf, 0x81, 0x17, 0xbf, 0xb3, 0x64, 0x13, 0xdb, 0x06, 0xd2, 0xb4,
	0xbd, 0xcd, 0x64, 0x5f, 0x7e, 0x6f, 0x92, 0x79, 0x0b, 0x6e, 0x28, 0x27, 0xbe, 0x9c, 0x09, 0x2d,
	0xf0, 0x34, 0x96, 0x73, 0x35, 0xa6, 0x99, 0xaf, 0x66, 0x5f, 0x7e, 0x1c, 0x6a, 0x5a, 0x84, 0x4b,
	0xef, 0x11, 0x60, 0x48, 0x8b, 0x80, 0x3e, 0xe7, 0xa4, 0x34, 0x9e, 0x81, 0xdd, 0x95, 0xb2, 0x1f,
	0x71, 0xab, 0x6d, 0x75, 0xec, 0x20, 0x6f, 0x10, 0xa1, 0x39, 0x1a, 0x4d, 0x22, 0xde, 0x68, 0x5b,
	0x1d, 0x37, 0x30, 0x35, 0x9e, 0x00, 0x7b, 0xa6, 0x25, 0x67, 0x46, 0x97, 0x95, 0xde, 0x1d, 0x1c,
	0xf5, 0x12, 0xa1, 0xe8, 0x60, 0x96, 0xf7, 0x6d, 0xc1, 0xf1, 0xeb, 0x5c, 0x8d, 0x5f, 0xd2, 0xc3,
	0x5f, 0xce, 0x94, 0x03, 0x15, 0xf7, 0x23, 0x33, 0x8a, 0x1b, 0xe4, 0x0d, 0xb6, 0xc0, 0x7d, 0x9b,
	0x4c, 0x49, 0xe9, 0x70, 0x2a, 0x79, 0xd3, 0x9c, 0xac, 0x1f, 0x20, 0x07, 0xa7, 0x27, 0x52, 0x4d,
	0xa9, 0xe6, 0xb6, 0x39, 0xfb, 0x6b, 0x3d, 0x9d, 0x4f, 0xd2, 0x95, 0xb2, 0x7e, 0x92, 0x95, 0x6b,
	0x63, 0xab, 0x2b, 0xab, 0x71, 0x6d, 0x96, 0x5d, 0xdf, 0x0b, 0xd7, 0x24, 0xd9, 0x70, 0xcd, 0xf9,
	0xd6, 0x56, 0x7e, 0xa3, 0x86, 0xcf, 0xca, 0xfc, 0x6b, 0x70, 0x02, 0x52, 0x52, 0xa4, 0xe6, 0x17,
	0xf6, 0x44, 0x44, 0xc5, 0xd7, 0x98, 0x3a, 0xdb, 0xe5, 0x40, 0xc5, 0x05, 0x30, 0x2b, 0x6f, 0x7e,
	0x18, 0x38, 0x0f, 0x79, 0x42, 0xf0, 0x1e, 0xd8, 0x90, 0x16, 0x78, 0xe1, 0x57, 0xc4, 0xc7, 0x5f,
	0x67, 0xe7, 0xbc, 0x55, 0x29, 0x28, 0x7c, 0xbd, 0x7f, 0xf8, 0x04, 0xb6, 0xc9, 0x07, 0x5e, 0x56,
	0x0a, 0x37, 0xb3, 0xb3, 0x93, 0x35, 0x04, 0xa7, 0x08, 0x0c, 0x5e, 0x55, 0x4a, 0xcb, 0x71, 0xda,
	0x97, 0xd7, 0x95, 0xb2, 0x86, 0xb7, 0x0e, 0xc5, 0xde, 0xbc, 0x24, 0xa9, 0xe3, 0xad, 0xd6, 0xbd,
	0x8b, 0xf7, 0xf1, 0xdf, 0xdc, 0xe0, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xa0, 0xf2,
	0x5d, 0xce, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayClient interface {
	New(ctx context.Context, in *NewRequest, opts ...grpc.CallOption) (*Respond, error)
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*Respond, error)
	PushOne(ctx context.Context, in *PushOneRequest, opts ...grpc.CallOption) (*Respond, error)
	PushApp(ctx context.Context, in *PushAppRequest, opts ...grpc.CallOption) (*Respond, error)
	PushAll(ctx context.Context, in *PushAllRequest, opts ...grpc.CallOption) (*Respond, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) New(ctx context.Context, in *NewRequest, opts ...grpc.CallOption) (*Respond, error) {
	out := new(Respond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.gateway.Gateway/New", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*Respond, error) {
	out := new(Respond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.gateway.Gateway/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) PushOne(ctx context.Context, in *PushOneRequest, opts ...grpc.CallOption) (*Respond, error) {
	out := new(Respond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.gateway.Gateway/PushOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) PushApp(ctx context.Context, in *PushAppRequest, opts ...grpc.CallOption) (*Respond, error) {
	out := new(Respond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.gateway.Gateway/PushApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) PushAll(ctx context.Context, in *PushAllRequest, opts ...grpc.CallOption) (*Respond, error) {
	out := new(Respond)
	err := c.cc.Invoke(ctx, "/gpusher.srv.gateway.Gateway/PushAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
type GatewayServer interface {
	New(context.Context, *NewRequest) (*Respond, error)
	Close(context.Context, *CloseRequest) (*Respond, error)
	PushOne(context.Context, *PushOneRequest) (*Respond, error)
	PushApp(context.Context, *PushAppRequest) (*Respond, error)
	PushAll(context.Context, *PushAllRequest) (*Respond, error)
}

// UnimplementedGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedGatewayServer struct {
}

func (*UnimplementedGatewayServer) New(ctx context.Context, req *NewRequest) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method New not implemented")
}
func (*UnimplementedGatewayServer) Close(ctx context.Context, req *CloseRequest) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (*UnimplementedGatewayServer) PushOne(ctx context.Context, req *PushOneRequest) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushOne not implemented")
}
func (*UnimplementedGatewayServer) PushApp(ctx context.Context, req *PushAppRequest) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushApp not implemented")
}
func (*UnimplementedGatewayServer) PushAll(ctx context.Context, req *PushAllRequest) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushAll not implemented")
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.gateway.Gateway/New",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).New(ctx, req.(*NewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.gateway.Gateway/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_PushOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).PushOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.gateway.Gateway/PushOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).PushOne(ctx, req.(*PushOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_PushApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).PushApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.gateway.Gateway/PushApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).PushApp(ctx, req.(*PushAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_PushAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).PushAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpusher.srv.gateway.Gateway/PushAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).PushAll(ctx, req.(*PushAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gpusher.srv.gateway.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "New",
			Handler:    _Gateway_New_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Gateway_Close_Handler,
		},
		{
			MethodName: "PushOne",
			Handler:    _Gateway_PushOne_Handler,
		},
		{
			MethodName: "PushApp",
			Handler:    _Gateway_PushApp_Handler,
		},
		{
			MethodName: "PushAll",
			Handler:    _Gateway_PushAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
